CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    username VARCHAR(25) NOT NULL UNIQUE,

    password_hash TEXT NOT NULL,

    search_opt_out BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE contacts (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    contact_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    PRIMARY KEY (user_id, contact_id),
    CONSTRAINT contacts_no_self CHECK (user_id <> contact_id)
);


CREATE TABLE blocks (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    blocked_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    PRIMARY KEY (user_id, blocked_id),
    CONSTRAINT blocks_no_self CHECK (user_id <> blocked_id)
);


CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    type VARCHAR(10) NOT NULL,

    group_creator_id BIGINT REFERENCES users(id) ON DELETE CASCADE,

    direct_user_id1 BIGINT REFERENCES users(id) ON DELETE CASCADE,
    direct_user_id2 BIGINT REFERENCES users(id) ON DELETE CASCADE,

    last_seq BIGINT NOT NULL DEFAULT 0,
    last_message_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT rooms_type_check CHECK (type IN ('DIRECT', 'GROUP')),

    CONSTRAINT rooms_type_user_fk CHECK (
        (type = 'DIRECT'
            AND group_creator_id IS NULL
            AND direct_user_id1 IS NOT NULL
            AND direct_user_id2 IS NOT NULL
            AND direct_user_id1 < direct_user_id2)
        OR
        (type = 'GROUP'
            AND group_creator_id IS NOT NULL
            AND direct_user_id1 IS NULL
            AND direct_user_id2 IS NULL)
    )
);
CREATE UNIQUE INDEX uniq_direct_room ON rooms (direct_user_id1, direct_user_id2)
    WHERE type = 'DIRECT';
CREATE INDEX idx_rooms_last_message_at ON rooms(last_message_at DESC);


CREATE TABLE room_members (
    room_id BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    last_ack BIGINT NOT NULL,

    has_muted BOOLEAN NOT NULL DEFAULT FALSE,

    joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (room_id, user_id)
);
CREATE INDEX idx_room_members_user_id ON room_members(user_id);


CREATE TABLE messages (
    room_id BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    seq BIGINT NOT NULL,

    kind VARCHAR(10) NOT NULL,
    event_type VARCHAR(30),

    content TEXT,
    event_data JSONB,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (room_id, seq),

    CONSTRAINT messages_kind_check CHECK (kind IN ('USER', 'EVENT')),

    CONSTRAINT messages_kind_shape_check CHECK (
        (kind = 'USER'
            AND event_type IS NULL
            AND content IS NOT NULL
            AND BTRIM(content) <> ''
            AND event_data IS NULL)
        OR
        (kind = 'EVENT'
            AND event_type IS NOT NULL
            AND content IS NULL
            AND event_data IS NOT NULL)
    ),

    CONSTRAINT messages_event_type_check CHECK (
        event_type IS NULL
        OR event_type IN (
            'GROUP_CREATED',
            'MEMBER_JOINED',
            'MEMBER_LEFT',
            'MEMBER_REMOVED'
        )
    )
);
